# Generated by Django 4.2.5 on 2023-11-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='message',
            name='print_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='printing/'),
        ),
    ]
