# Generated by Django 4.2.5 on 2023-11-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_message_options_message_print_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='print_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Messages/'),
        ),
    ]
